ARG GO_DOCKER_VERSION=1.24.0

FROM golang:${GO_DOCKER_VERSION}-alpine AS base

ENV CGO_ENABLED=0 \
    GOOS=linux \
    GOARCH=amd64

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

FROM base AS tester

COPY . .
RUN go test -v ./...

FROM base AS builder

COPY . .
RUN go build -ldflags="-s -w" -o /app/app ./cmd/app/main.go

FROM alpine:latest AS runner

WORKDIR /app
COPY --from=builder /app/app .

EXPOSE 8080
CMD ["./app"]
