
name: lock-stock-v2

services:
  go:
    image: lock-stock-v2:development
    build:
      context: ../app
      dockerfile: ../docker/images/alpine/Dockerfile.development
    container_name: lock-stock-v2-go-development
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
      - public
    ports:
      - "8080:${APP_LISTEN_PORT:-8080}"

  postgres:
    image: postgres:17-alpine
    container_name: lock-stock-v2-postgres-development
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_database
    networks:
      - internal
    volumes:
      - ./volumes/development/postgres_data:/var/lib/postgresql/data:cached
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U db_user -d db_database"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  internal:
    driver: bridge
    internal: true
  public:
    driver: bridge
    internal: false
