name: lock-stock-v2

services:
  go:
    image: lock-stock-v2:development
    build:
      context: ../app
      dockerfile: ../docker/images/alpine/Dockerfile.development
    container_name: lock-stock-v2-go-development
    restart: always
    user: "1001:1001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
      - public
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17-alpine
    container_name: lock-stock-v2-postgres-development
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_database
    networks:
      internal:
        aliases:
          - postgres
      public:
        aliases:
          - postgres-public
    ports:
      - "8661:5432"
    volumes:
      - ./volumes/development/postgres_data:/var/lib/postgresql/data:cached
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_user -d db_database" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: lock-stock-v2-migrate
    user: "1000:1000"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [ "tail", "-f", "/dev/null" ]
    volumes:
      - ../app/migrations:/migrations
    networks:
      - internal

  zookeeper:
    container_name: lock-stock-v2-zookeeper
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    container_name: lock-stock-v2-kafka
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  tests:
    image: lock-stock-v2:tests
    build:
      context: ../app
      dockerfile: ../docker/images/alpine/Dockerfile.development
      target: tester
    container_name: lock-stock-v2-tests
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
    entrypoint: [ "go", "test", "-v", "./..." ]

networks:
  internal:
    driver: bridge
    internal: true
  public:
    driver: bridge
    internal: false
