name: lock-stock-v2

services:
  go:
    image: lock-stock-v2:development
    build:
      context: ../app
      dockerfile: ../docker/images/alpine/Dockerfile.development
    container_name: lock-stock-v2-go-development
    restart: always
    user: "1001:1001"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal
      - public
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17-alpine
    container_name: lock-stock-v2-postgres-development
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
      POSTGRES_DB: db_database
    networks:
      internal:
        aliases:
          - postgres
      public:
        aliases:
          - postgres-public
    ports:
      - "8661:5432"
    volumes:
      - ./volumes/development/postgres_data:/var/lib/postgresql/data:cached
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U db_user -d db_database" ]
      interval: 10s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    container_name: lock-stock-v2-migrate
    user: "1000:1000"
    depends_on:
      postgres:
        condition: service_healthy
    entrypoint: [ "tail", "-f", "/dev/null" ]
    volumes:
      - ../app/migrations:/migrations
    networks:
      - internal

networks:
  internal:
    driver: bridge
    internal: true
  public:
    driver: bridge
    internal: false
