openapi: 3.0.0
info:
  title: Lock Stock API
  version: 1.0.0

paths:
  /ws/{roomId}:
    get:
      summary: Установить WebSocket-соединение
      description: Создаёт WebSocket-соединение для указанной комнаты.
      operationId: connectWebSocket
      tags:
        - WebSocket
      parameters:
        - name: roomId
          in: path
          required: true
          description: Уникальный идентификатор комнаты
          schema:
            type: string
            format: uuid
            example: "550e8400-e29b-41d4-a716-446655440000"
      security: [ ]
      responses:
        "101":
          description: WebSocket-соединение установлено
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "WebSocket connection established"
        "400":
          description: Ошибка соединения (например, отсутствует roomId)
          content:
            text/plain:
              schema:
                type: string
                example: "Missing room_id"
        "500":
          description: Ошибка при установлении соединения
          content:
            text/plain:
              schema:
                type: string
                example: "Failed to upgrade connection"